[[Aura Ultra]]
  palette = "#221931:#ff6767:#61ffca:#ffd49b:#82e2ff:#f694ff:#72f1e5:#c8bff2:#4e3e63:#ff6767:#61ffca:#ffd49b:#82e2ff:#f694ff:#72f1e5:#a277ff"
  background_color = "#2a1f3d"
  foreground_color = "#edecee"
  