# vim: ft=dosini
#
# aerc AuraUltra styleset
# set styleset-name=aura-ultra-xxx.ini in 'aerc.conf' to load the style
#

*.default=true
*.normal=true

border.fg=#3b2f4f
border.bg=#2a1f3d

title.fg=#221931
title.bg=#82e2ff
title.bold=true

header.fg=#ff6767
#header.bg=#2a1f3d
header.bold=true

tab.fg=#3b2f4f
tab.bg=#2a1f3d
tab.selected.fg=#221931
tab.selected.bg=#82e2ff

statusline_default.fg=#edecee
statusline_default.bg=#23182f
statusline_error.fg=#cc5252
statusline_success.fg=#7dffd4

*error.bold=true
*error.fg=#cc5252
*warning.fg=#ffd49b
*success.fg=#7dffd4

dirlist_*.bg=#2a1f3d
dirlist_*.fg=#edecee
dirlist_*.selected.bg=#2b2d43
dirlist_*.selected.fg=#edecee

msglist_*.bg=#2a1f3d
msglist_*.fg=#edecee
msglist_*.selected.bg=#2b2d43
#msglist_*.selected.fg=#edecee
msglist_unread.bold=true
msglist_unread.fg=#82e2ff
msglist_marked.fg=#ffca85
msglist_thread_folded.italic=true
msglist_thread_folded.underline=true
msglist_gutter.bg=#211f2f
msglist_pill.bg=#3b2f4f
msglist_pill.reverse=false

part_*.fg=#edecee
part_*.bg=#23182f
part_*.selected.fg=#edecee
part_*.selected.bg=#3b2f4f

completion_default.bg=#23182f
completion_default.fg=#edecee
completion_default.selected.bg=#3b2f4f
completion_default.selected.fg=#edecee
completion_gutter.bg=#211f2f
completion_pill.bg=#3b2f4f
completion_pill.reverse=false

spinner.bg=#2a1f3d
spinner.fg=#edecee

selector_focused.bold=false
selector_focused.bg=#2b2d43
selector_focused.fg=#edecee
selector_chooser.bold=false
selector_chooser.bg=#2b2d43
selector_chooser.fg=#edecee
default.selected.bold=false
default.selected.fg=#edecee
default.selected.bg=#2b2d43

[viewer]
url.underline=true
url.fg=#7a6f9b
header.fg=#a277ff
signature.fg=#f694ff
diff_add.fg=#455765
diff_del.fg=#532c42
diff_meta.bold=true
diff_chunk.dim=true
quote_1.fg=#ffd49b
quote_2.fg=#61ffca
quote_3.fg=#72f1e5
quote_3.dim=true
quote_4.fg=#82e2ff
quote_4.dim=true
quote_x.fg=#6e5f8f
quote_x.dim=true

