# -----------------------------------------------------------------------------
# AuraUltra Alacritty Colors
# Theme: Aura Ultra
# Upstream: https://github.com/minhtri2710/aura-ultra.nvim/raw/main/extras/alacritty/aura-ultra_dark.toml
# -----------------------------------------------------------------------------

# Default colors
[colors.primary]
background = '#2a1f3d'
foreground = '#edecee'

# Normal colors
[colors.normal]
black = '#221931'
red = '#ff6767'
green = '#61ffca'
yellow = '#ffd49b'
blue = '#82e2ff'
magenta = '#f694ff'
cyan = '#72f1e5'
white = '#c8bff2'

# Bright colors
[colors.bright]
black = '#3b2f4a'
red = '#ff8080'
green = '#c9ffe8'
yellow = '#ffe5c8'
blue = '#b5ebff'
magenta = '#f7abff'
cyan = '#8bfef3'
white = '#edecee'
