# vim:ft=kitty

## name: Aura Ultra
## license: MIT
## author: Folke Lemaitre
## upstream: https://github.com/minhtri2710/aura-ultra.nvim/raw/main/extras/kitty/aura-ultra_dark.conf


background #2a1f3d
foreground #edecee
selection_background #2b2d43
selection_foreground #edecee
url_color #7dffd4
cursor #edecee
cursor_text_color #2a1f3d

# Tabs
active_tab_background #82e2ff
active_tab_foreground #23182f
inactive_tab_background #211f2f
inactive_tab_foreground #5a4d7a
#tab_bar_background #221931

# Windows
active_border_color #82e2ff
inactive_border_color #211f2f

# normal
color0 #221931
color1 #ff6767
color2 #61ffca
color3 #ffd49b
color4 #82e2ff
color5 #f694ff
color6 #72f1e5
color7 #c8bff2

# bright
color8  #786395
color9  #ff8080
color10 #c9ffe8
color11 #ffe5c8
color12 #b5ebff
color13 #f7abff
color14 #8bfef3
color15 #edecee

# extended colors
color16 #ffca85
color17 #cc5252
