# -----------------------------------------------------------------------------
# Theme: Aura Ultra
# Upstream: https://github.com/minhtri2710/aura-ultra.nvim/raw/main/extras/termux/aura-ultra_dark.properties
# -----------------------------------------------------------------------------

background: #2a1f3d
foreground: #edecee

# Normal colors
color0:  #221931
color1:  #ff6767
color2:  #61ffca
color3:  #ffd49b
color4:  #82e2ff
color5:  #f694ff
color6:  #72f1e5
color7:  #c8bff2

# Bright colors
color8:  #786395
color9:  #ff8080
color10: #c9ffe8
color11: #ffe5c8
color12: #b5ebff
color13: #f7abff
color14: #8bfef3
color15: #edecee

# Extended colors
color16: #ffca85
color17: #cc5252
